"""updates crimerate model

Revision ID: 406e946c2bb5
Revises: 950793b28294
Create Date: 2021-07-22 01:38:27.895909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '406e946c2bb5'
down_revision = '950793b28294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crimerate', 'crime_index',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(asdecimal=False),
               existing_nullable=True)
    op.alter_column('crimerate', 'safety_index',
               existing_type=sa.INTEGER(),
               type_=sa.DECIMAL(asdecimal=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crimerate', 'safety_index',
               existing_type=sa.DECIMAL(asdecimal=False),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('crimerate', 'crime_index',
               existing_type=sa.DECIMAL(asdecimal=False),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
